### ISSUE TITLE
EventEmitterModule crash with TypeError from reflect-metadata stack when used with Proxy

### ISSUE THREAD

**Issue by zackdotcomputer** [nestjs/event-emitter#1008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We have an AppModule that includes many modules. This is a bad interaction between two in particular:
1. The EventEmitter module.
2. A PrismaModule that uses the `$extends` function to add client features.

Strangely, when the factory function finishes adding the PrismaModule using the `$extends` function, the `EventEmitter` crashes with the following stack trace:
```
/Users/zack/code/learning/bug-repro/node_modules/reflect-metadata/Reflect.js:354
                throw new TypeError();
                      ^
TypeError: 
    at Reflect.getMetadata (/Users/zack/code/learning/bug-repro/node_modules/reflect-metadata/Reflect.js:354:23)
    at Reflector.get (/Users/zack/code/learning/bug-repro/node_modules/@nestjs/core/services/reflector.service.js:39:24)
    at EventsMetadataAccessor.getEventHandlerMetadata (/Users/zack/code/learning/bug-repro/node_modules/@nestjs/event-emitter/lib/events-metadata.accessor.ts:13:37)
    at EventSubscribersLoader.subscribeToEventIfListener (/Users/zack/code/learning/bug-repro/node_modules/@nestjs/event-emitter/lib/event-subscribers.loader.ts:76:29)
    at /Users/zack/code/learning/bug-repro/node_modules/@nestjs/event-emitter/lib/event-subscribers.loader.ts:59:18
    at MetadataScanner.scanFromPrototype (/Users/zack/code/learning/bug-repro/node_modules/@nestjs/core/metadata-scanner.js:34:31)
    at /Users/zack/code/learning/bug-repro/node_modules/@nestjs/event-emitter/lib/event-subscribers.loader.ts:55:30
    at Array.forEach (<anonymous>)
    at EventSubscribersLoader.loadEventListeners (/Users/zack/code/learning/bug-repro/node_modules/@nestjs/event-emitter/lib/event-subscribers.loader.ts:51:8)
    at EventSubscribersLoader.onApplicationBootstrap (/Users/zack/code/learning/bug-repro/node_modules/@nestjs/event-emitter/lib/event-subscribers.loader.ts:39:10)
```

This appears to be because Prisma's `$extend` function creates a `Proxy` object. Event-emitter tries to get the prototype of the proxied object, which returns the underlying class, and then get its keys. It then tries to iterate these keys on the Proxy and assumes they will all be defined. However, `Proxy` objects are free to redefine keys to be undefined or primitive values. When one of these is passed to `reflect-metadata`, it then crashes with this type error.

### Minimum reproduction code

https://github.com/zackdotcomputer/nest-event-bugreport

### Steps to reproduce

1. `npm i`
2. `npm start:dev`

Observe crash

### Expected behavior

The startup process should not crash. Instead, if the event-emitter receives a result in its iteration that is neither an object nor a function, it should not pass it on to reflect-metadata.

### Package version

2.0.2

### NestJS version

10.2.7

### Node.js version

18.18.0

### In which operating systems have you tested?

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/event-emitter/pull/1009
